<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>bitcoin Application</title>
    <link href="//fonts.googleapis.com/css?family=Lato:300" rel="stylesheet" type="text/css">
    <style>
        body {margin: 50px 0 0 0;padding: 0;width: 100%;font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;text-align: center;color: #aaa;font-size: 18px;}
        .page h1 {color: #719e40;letter-spacing: 0px;font-family: 'Lato', sans-serif;font-size: 40px;font-weight: 200;margin-bottom: 0;}
        .page div.nav a{padding: 7px;background: #111; display:inline-block; border-radius: 5px;color: #ee0;text-decoration: none;}
        .page div.nav{ margin-top:10px; display:block; }
        .page div.sec{ display:block;clear:both; height:10px; width:100%;}
    </style>
</head>
<body>
    <div class="page">
        <h1>Bitcoin Application</h1>
        <div class="nav">
            <a href="/info">Info</a>
            <a href="/info/inputs">/info/inputs</a>
            <a href="/info/outputs">/info/outputs</a>
            <div class="sec"></div>
            <a href="/tx/create">Create a Transaction</a>
            <a href="/tx/list">List transactions</a>
        </div>
    </div>

</body>
</html>
